development:
  adapter: postgresql
  encoding: unicode
  database: db/development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: db/test
  pool: 5
  timeout: 5000

production:
  uri: <%= ENV['DATABASE_URL'] %>
